/** @format */

import assets from "./assets";

const NFTData = [
	{
		// id: "NFT-01",
		// name: "Abstracto #312",
		// creator: "Putri Intan",
		// price: 4.25,
		id: 1,
		gymName: "Unique Gym",
		gymAdress: "DHA PHASE 2",
		gymNumber: "+21-111-6573214",
		emailAddress: "flexgym@gym.com",
		monthlyFee: 6890,
		registrationFee: 8000,
		website: "wwww.flexgym.com",
		timings: "5:00 PM - 12:00 AM",
		description:
			"The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
		image: assets.nft01,
		trainers: [
			{
				id: "BID-11",
				name: "Jessica Tan",
				price: 4255,
				image: assets.person02,
				rating: "4.5",
			},
			{
				id: "BID-12",
				name: "Jennifer Sia",
				price: 4508,
				image: assets.person03,
				rating: "4.5",
			},
			{
				id: "BID-13",
				name: "Rosie Wong",
				price: 4000,
				image: assets.person04,
				rating: "4.5",
			},
		],
	},
	{
		id: 2,
		gymName: "Sunshine Gym",
		gymAdress: "DHA PHASE 2",
		gymNumber: "+21-111-6573214",
		emailAddress: "flexgym@gym.com",
		monthlyFee: 6890,
		registrationFee: 8000,
		website: "wwww.flexgym.com",
		timings: "5:00 PM - 12:00 AM",
		description:
			"The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
		image: assets.nft02,
		trainers: [
			{
				id: "BID-11",
				name: "Jessica Tan",
				price: 4255,
				image: assets.person02,
				rating: "4.5",
			},
			{
				id: "BID-12",
				name: "Jennifer Sia",
				price: 4508,
				image: assets.person03,
				rating: "4.5",
			},
			{
				id: "BID-13",
				name: "Rosie Wong",
				price: 4000,
				image: assets.person04,
				rating: "4.5",
			},
		],
	},
	{
		id: 3,
		gymName: "Flex Gym",
		gymAdress: "DHA PHASE 2",
		gymNumber: "+21-111-6573214",
		emailAddress: "flexgym@gym.com",
		monthlyFee: 6890,
		registrationFee: 8000,
		website: "wwww.flexgym.com",
		timings: "5:00 PM - 12:00 AM",
		description:
			"The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
		image: assets.nft03,
		trainers: [
			{
				id: "BID-11",
				name: "Jessica Tan",
				price: 4255,
				image: assets.person02,
				rating: "4.5",
			},
			{
				id: "BID-12",
				name: "Jennifer Sia",
				price: 4508,
				image: assets.person03,
				rating: "4.5",
			},
			{
				id: "BID-13",
				name: "Rosie Wong",
				price: 4000,
				image: assets.person04,
				rating: "4.5",
			},
		],
	},
	{
		id: 4,
		gymName: "Flex Gym",
		gymAdress: "DHA PHASE 2",
		gymNumber: "+21-111-6573214",
		emailAddress: "flexgym@gym.com",
		monthlyFee: 6890,
		registrationFee: 8000,
		website: "wwww.flexgym.com",
		timings: "5:00 PM - 12:00 AM",
		description:
			"The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
		image: assets.nft04,
		trainers: [
			{
				id: "BID-11",
				name: "Jessica Tan",
				price: 4255,
				image: assets.person02,
				rating: "4.5",
			},
			{
				id: "BID-12",
				name: "Jennifer Sia",
				price: 4508,
				image: assets.person03,
				rating: "4.5",
			},
			{
				id: "BID-13",
				name: "Rosie Wong",
				price: 4000,
				image: assets.person04,
				rating: "4.5",
			},
		],
	},
	{
		id: 5,
		gymName: "Flex Gym",
		gymAdress: "DHA PHASE 2",
		gymNumber: "+21-111-6573214",
		emailAddress: "flexgym@gym.com",
		monthlyFee: 6890,
		registrationFee: 8000,
		website: "wwww.flexgym.com",
		timings: "5:00 PM - 12:00 AM",
		description:
			"The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
		image: assets.nft05,
		trainers: [
			{
				id: "BID-11",
				name: "Jessica Tan",
				price: 4255,
				image: assets.person02,
				rating: "4.5",
			},
			{
				id: "BID-12",
				name: "Jennifer Sia",
				price: 4508,
				image: assets.person03,
				rating: "4.5",
			},
			{
				id: "BID-13",
				name: "Rosie Wong",
				price: 4000,
				image: assets.person04,
				rating: "4.5",
			},
		],
	},
	{
		id: 6,
		gymName: "Flex Gym",
		gymAdress: "DHA PHASE 2",
		gymNumber: "+21-111-6573214",
		emailAddress: "flexgym@gym.com",
		monthlyFee: 6890,
		registrationFee: 8000,
		website: "wwww.flexgym.com",
		timings: "5:00 PM - 12:00 AM",
		description:
			"The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
		image: assets.nft06,
		trainers: [
			{
				id: "BID-11",
				name: "Jessica Tan",
				price: 4255,
				image: assets.person02,
				rating: "4.5",
			},
			{
				id: "BID-12",
				name: "Jennifer Sia",
				price: 4508,
				image: assets.person03,
				rating: "4.5",
			},
			{
				id: "BID-13",
				name: "Rosie Wong",
				price: 4000,
				image: assets.person04,
				rating: "4.5",
			},
		],
	},
	{
		id: 7,
		gymName: "Flex Gym",
		gymAdress: "DHA PHASE 2",
		gymNumber: "+21-111-6573214",
		emailAddress: "flexgym@gym.com",
		monthlyFee: 6890,
		registrationFee: 8000,
		website: "wwww.flexgym.com",
		timings: "5:00 PM - 12:00 AM",
		description:
			"The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
		image: assets.nft07,
		trainers: [
			{
				id: "BID-11",
				name: "Jessica Tan",
				price: 4255,
				image: assets.person02,
				rating: "4.5",
			},
			{
				id: "BID-12",
				name: "Jennifer Sia",
				price: 4508,
				image: assets.person03,
				rating: "4.5",
			},
			{
				id: "BID-13",
				name: "Rosie Wong",
				price: 4000,
				image: assets.person04,
				rating: "4.5",
			},
		],
	},
];
// {
//   id: "NFT-02",
//   name: "Green Coins",
//   creator: "Siti Nurhaliza",
//   price: 7.25,
//   description:
//     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
//   image: assets.nft02,
//   bids: [
//     {
//       id: "BID-21",
//       name: "Jessica Tan",
//       price: 7.05,
//       image: assets.person04,
//       date: "December 12, 2019 at 12:10 PM",
//     },
//   ],
// },
// {
//   id: "NFT-03",
//   name: "NFT coins race",
//   creator: "Elisabeth aho",
//   price: 95.25,
//   description:
//     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
//   image: assets.nft03,
//   bids: [
//     {
//       id: "BID-31",
//       name: "Jessica Tan",
//       price: 95.25,
//       image: assets.person02,
//       date: "December 12, 2019 at 12:10 PM",
//     },
//     {
//       id: "BID-32",
//       name: "Jennifer Sia",
//       price: 95.5,
//       image: assets.person03,
//       date: "December 27, 2019 at 1:50 PM",
//     },
//   ],
// },
// {
//   id: "NFT-04",
//   name: "Nifty NFT",
//   creator: "Putri Intan",
//   price: 54.25,
//   description:
//     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur.",
//   image: assets.nft04,
//   bids: [
//     {
//       id: "BID-41",
//       name: "Jessica Tan",
//       price: 56.25,
//       image: assets.person02,
//       date: "December 12, 2019 at 12:10 PM",
//     },
//     {
//       id: "BID-42",
//       name: "Jennifer Sia",
//       price: 54.25,
//       image: assets.person03,
//       date: "December 27, 2019 at 1:50 PM",
//     },
//     {
//       id: "BID-43",
//       name: "Rosie Wong",
//       price: 55.15,
//       image: assets.person04,
//       date: "December 31, 2019 at 3:50 PM",
//     },
//     {
//       id: "BID-44",
//       name: "Vincent Swift",
//       price: 54.15,
//       image: assets.person02,
//       date: "December 31, 2019 at 3:50 PM",
//     },
//   ],
// },
// {
//   id: "NFT-05",
//   name: "Colorful circles",
//   creator: "David doe",
//   price: 10.25,
//   description:
//     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural.",
//   image: assets.nft05,
//   bids: [
//     {
//       id: "BID-51",
//       name: "Jessica Tan",
//       price: 10.25,
//       image: assets.person02,
//       date: "December 12, 2019 at 12:10 PM",
//     },
//   ],
// },
// {
//   id: "NFT-06",
//   name: "Black box model",
//   creator: "Leo Messi",
//   price: 20.25,
//   description:
//     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
//   image: assets.nft06,
//   bids: [
//     {
//       id: "BID-61",
//       name: "Jessica Tan",
//       price: 20.25,
//       image: assets.person02,
//       date: "December 12, 2019 at 12:10 PM",
//     },
//     {
//       id: "BID-62",
//       name: "Jennifer Sia",
//       price: 20.5,
//       image: assets.person03,
//       date: "December 27, 2019 at 1:50 PM",
//     },
//     {
//       id: "BID-63",
//       name: "Rosie Wong",
//       price: 20.75,
//       image: assets.person04,
//       date: "December 31, 2019 at 3:50 PM",
//     },
//     {
//       id: "BID-64",
//       name: "Siti Nurhaliza",
//       price: 21.25,
//       image: assets.person02,
//       date: "December 31, 2019 at 3:50 PM",
//     },
//     {
//       id: "BID-65",
//       name: "Kaitlyn Lee",
//       price: 7.25,
//       image: assets.person02,
//       date: "December 31, 2019 at 3:50 PM",
//     },
//   ],
// },
// {
//   id: "NFT-07",
//   name: "Abstracto soulful art",
//   creator: "Victor de la Cruz",
//   price: 18.25,
//   description:
//     "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
//   image: assets.nft07,
//   bids: [],
// },

export { NFTData };
